### ISSUE TITLE
Apply for Discord opensource

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/community-office-hours#12]
It might be worth applying for https://discord.com/open-source ✨

**Comment by pawlean** [comment]
@axonasif What are the benefits of applying to this?

**Comment by axonasif** [comment]
@pawlean I guess it could get us the verified tag and list our server on that page, there are some other perks too (like getting access to beta features early)
<img width="574" alt="Screenshot 2022-09-05 at 2 22 43 PM" src="https://user-images.githubusercontent.com/39482679/188403192-4c555f48-36c5-4b67-abf1-eee56e5ff64a.png">

**Comment by axonasif** [comment]
It was done a few days before, now waiting for the [PR](https://github.com/discord/discord-open-source/pull/456) to get merged.
