### ISSUE TITLE
Analyze Discord+Frontapp queries

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/community-office-hours#16]
Will collaborate with @YanicM :pray:

**Comment by pawlean** [comment]
This will be worked on after gitpod-io/optimus#37 is closed.

**Comment by axonasif** [comment]
Public indexing was addressed by https://github.com/gitpod-io/optimus/pull/40/commits/87bd06bb0c1f47169a807931d0cc7ab2a4e2390a and the subsequent commits.

I'll follow up with Yanic and others.

Docs:
- https://www.notion.so/gitpod/Gitpod-Community-096f164b378742cfb61a88babdd5626d?pvs=4#b1a20d54d38d4de89222a2a80882b119
