### ISSUE TITLE
Create Hero-specific swag

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/community-office-hours#24]
This is an idea dump for all the Hero-specific swag we could create for our superfans 🫶

**Comment by soup-bowl** [comment]
"Open in Gitpod" button stress ball!

**Comment by david-bakin** [comment]
Logo stickers - for plastering on a laptop.  I've always enjoyed getting a nice little notebook, fine paper, with logo.  And, for the programmer who really knows what's up: rubber duck, with logo (very suitable for temporarily lending to a colleague at work).

**Comment by soup-bowl** [comment]
> [...] **rubber duck**, with logo (very suitable for temporarily lending to a colleague at work).

+1 for this, for the [rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging). I've actually never seen this in all the events I've attended, so you might've picked up on a clever niche here.

**Comment by david-bakin** [comment]
> > [...] **rubber duck**, with logo (very suitable for temporarily lending to a colleague at work).
> 
> I've actually never seen this in all the events I've attended, so you might've picked up on a clever niche here.

Me neither. I had to buy one at [Bed Bath and Beyond](https://www.bedbathandbeyond.com/store/s/rubber-duck).  I leave it sitting on my desk in my office.  (BTW, for doubters:  The technique _does_ work! I estimate about 50-60% of the time ...)
